# This is a basic workflow to help you get started with Actions

name: request Hero Data

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      BASE_URL: "https://marvelrivalsapi.com/api/v1/"
      API_TOKEN: ${{ secrets.MARVEL_RIVALS_KEY}}
      DEV_DIARIES_URL: "dev-diaries"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Fetch Marvel Rivals Hero Stats
        run: |
          curl -H "x-api-key: ${API_TOKEN}" -X GET "${BASE_URL}${DEV_DIARIES_URL}" \
          -o data/latest/latest_dev_diaries.json 

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/
          git commit -m "Updated dev diaries"
          git push
     
