# This is a basic workflow to help you get started with Actions

name: request Hero Data

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: "15 */6 * * *"  # Runs every 6 hours (at minute 0)

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      BASE_URL: "https://mrapi.org/api/"
      API_TOKEN: ${{ secrets.API_KEY_RIVALS }}
      HEROES_URL: "heroes-stats/pc"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # we need curl
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev
      - name: Ensure data directory exists
        run: mkdir -p data

      - name: Fetch Marvel Rivals Hero Stats
        run: |
          curl -X GET "${BASE_URL}${HEROES_URL}" \
          -o data/latest_heroes.json

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/
          git commit -m "Updated heroes"
          git push
     
