name: Update Marvel Rivals Hero Stats & Leaderboards

on:
  schedule:
    - cron: "0 1 * * *"  # Runs once per day
  workflow_dispatch:  # Allows manual execution

jobs:
  update_hero_data:
    runs-on: ubuntu-latest
    env:
      BASE_URL: "https://mrapi.org/api/"
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install aiohttp
      
      - name: Ensure heroes directory exists
        run: mkdir -p data/heroes

      - name: Fetch All Heroes
        run: |
          curl -X GET "${BASE_URL}heroes" -o data/latest/heroes/all_heroes.json
          cat data/latest/heroes/all_heroes.json  # Print response for debugging

      - name: Extract Hero Slugs
        id: extract_heroes
        run: |
          if [ ! -s data/latest/heroes/all_heroes.json ]; then
            echo "⚠️ No heroes data found!"
            exit 1
          fi
          HEROES=$(jq -r '.[].slug' data/latest/heroes/all_heroes.json)
          echo "$HEROES" > heroes_list.txt
          echo "$HEROES"
      

      - name: Fetch Data for All Heroes
        run: |
          while read -r HERO; do
            echo "Processing: $HERO"
            curl -X GET "${BASE_URL}leaderboard/$HERO" -o "data/latest/heroes/latest_leaderboard_$HERO.json"
            python merge_hero_leaderboard.py "$HERO"
          done < heroes_list.txt

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git config pull.rebase true   # rebase
          git add data/
          git commit -m "Updated Heroes Leaderboard data" || echo "No changes to commit"
          git pull || echo "No changes to pull"
          git push || echo "No changes to push"
