# This is a basic workflow to help you get started with Actions

name: request Codes

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: "55 23 * * *"  # Runs at 23:55 every day

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      BASE_URL: "https://mrapi.org/api/"
      API_TOKEN: ${{ secrets.API_KEY_RIVALS }}
      CODES_URL: "codes"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Fetch Marvel Rivals Hero Stats
        run: |
          curl -X GET "${BASE_URL}${CODES_URL}" \
          -o data/latest/latest_codes.json

      - name: Check for new codes
        env:
          DISCORD_WEBHOOK_URLS: ${{ secrets.CODES_WEBHOOK }},${{ secrets.CODES_WEBHOOK_SIBEL_SCREAMZZ }}   # Pass the variable to the script
        run: python check_codes.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/
          git commit -m "Updated codes" || echo "No changes to commit"
          git push || echo "No changes to push"
               
