name: Rocket Report

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: "00 12 * * *"  # Runs at 18:00 every day

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      start_time: ${{ steps.get_time.outputs.start_time }}
      rocket_overall_winrate: ${{ steps.extract_rocket.outputs.rocket_overall_winrate }}
      rocket_win_rate_one_defensive: ${{ steps.extract_rocket.outputs.rocket_win_rate_one_defensive }}
      rocket_win_rate_no_punisher: ${{ steps.extract_rocket.outputs.rocket_win_rate_no_punisher }}
      rocket_win_rate_with_punisher: ${{ steps.extract_rocket.outputs.rocket_win_rate_with_punisher }}
    steps:  
      - name: Clone project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # gets git history for changelogs
          token: ${{ secrets.WORKFLOW_TOKEN }} 
      - name: Get Time
        id: get_time
        shell: bash
        run: |
          echo "start_time=$(TZ=":Europe/Berlin" date '+%m/%d/%Y')" >> $GITHUB_OUTPUT
      - name: Extract rocket info
        id: extract_rocket
        run: |
          rocket_overall_winrate=$(jq -r '.rocket_overall_winrate[0]' rendered/data.json | xargs)
          rocket_win_rate_one_defensive=$(jq -r '.rocket_win_rate_one_defensive[0]' rendered/data.json | xargs)
          rocket_win_rate_no_punisher=$(jq -r '.rocket_win_rate_no_punisher[0]' rendered/data.json | xargs)
          rocket_win_rate_with_punisher=$(jq -r '.rocket_win_rate_with_punisher[0]' rendered/data.json | xargs)
          
          echo "rocket_overall_winrate=$rocket_overall_winrate" >> $GITHUB_OUTPUT
          echo "rocket_win_rate_one_defensive=$rocket_win_rate_one_defensive" >> $GITHUB_OUTPUT
          echo "rocket_win_rate_no_punisher=$rocket_win_rate_no_punisher" >> $GITHUB_OUTPUT
          echo "rocket_win_rate_with_punisher=$rocket_win_rate_with_punisher" >> $GITHUB_OUTPUT
          


            
  twitter:
    needs: setup
    runs-on: ubuntu-latest
    steps:  
      - name: Clone project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # gets git history for changelogs
          token: ${{ secrets.WORKFLOW_TOKEN }} 
      - uses: nearform-actions/github-action-notify-twitter@v1.2.3
        with:
          message: |
            🔥 @MarvelRivals Rocket Report for ${{ needs.setup.outputs.start_time }} 🔥
            Rocket Overall Winrate: ${{ needs.setup.outputs.rocket_overall_winrate }}
            Rocket Winrate with only one def Ult: ${{ needs.setup.outputs.rocket_win_rate_no_punisher }}
            Rocket Winrate with Ammo Overload: ${{ needs.setup.outputs.rocket_win_rate_with_punisher }}
            Rocket Winrate without Ammo Overload: ${{ needs.setup.outputs.rocket_win_rate_one_defensive }}
            Full data & analysis: https://rivalsstats.com/
            #MarvelRivals #Tierlist

          twitter-app-key: ${{ secrets.TWITTER_APP_KEY }}
          twitter-app-secret: ${{ secrets.TWITTER_APP_SECRET }}
          twitter-access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          twitter-access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          media: |
            ./rendered/RocketHate.png
          media-alt-text: |
            Rocket Stats
  reddit:
      runs-on: ubuntu-latest
      needs: setup
      steps:
        - name: reddit
          uses: meysam81/reddit-scheduled-submit@v1.1.1
          with:
            username: ${{ secrets.REDDIT_USERNAME }}
            password: ${{ secrets.REDDIT_PASSWORD }}
            client-id: ${{ secrets.REDDIT_APP_ID }}
            client-secret: ${{ secrets.REDDIT_APP_SECRET }}
            subreddit: ${{ secrets.REDDIT_SUBREDDIT }}
            title: "🔥 Rocket Report for ${{ needs.setup.outputs.start_time }}! 🔥"
            message: |
              Rocket Overall Winrate: ${{ needs.setup.outputs.rocket_overall_winrate }}

              Rocket Winrate with only one def Ult: ${{ needs.setup.outputs.rocket_win_rate_no_punisher }}

              Rocket Winrate with Ammo Overload: ${{ needs.setup.outputs.rocket_win_rate_with_punisher }}

              Rocket Winrate without Ammo Overload: ${{ needs.setup.outputs.rocket_win_rate_one_defensive }}

        
              Full data & analysis: https://rivalsstats.com/
  bsky-post:
      runs-on: ubuntu-latest
      needs: setup
      steps:
        - name: Clone project
          uses: actions/checkout@v3
          with:
            fetch-depth: 0  # gets git history for changelogs
            token: ${{ secrets.WORKFLOW_TOKEN }} 

        # Install pngquant for image compression
        - name: Install pngquant
          run: |
            sudo apt-get update
            sudo apt-get install -y pngquant
    
        # Compress the PNG file to reduce its size
        - name: Compress RocketHate.png
          run: |
            pngquant --quality=65-80 --force --output ./rendered/RocketHate-compressed.png ./rendered/RocketHate.png

        - uses: myConsciousness/bluesky-post@v5
          with:
            text: |
              🔥 @marvel-rivals.bsky.social‬ Rocket Report for ${{ needs.setup.outputs.start_time }}! 🔥
              Rocket Overall Winrate: ${{ needs.setup.outputs.rocket_overall_winrate }}
              Rocket Winrate with only one def Ult: ${{ needs.setup.outputs.rocket_win_rate_no_punisher }}
              Rocket Winrate with Ammo Overload: ${{ needs.setup.outputs.rocket_win_rate_with_punisher }}
              Rocket Winrate without Ammo Overload: ${{ needs.setup.outputs.rocket_win_rate_one_defensive }} 
              [Full data & analysis](https://rivalsstats.com)
              #MarvelRivals #Tierlist
            media: "./rendered/RocketHate-compressed.png"
            media-alt: "Rocket Stats"
            identifier: ${{ secrets.BLUESKY_IDENTIFIER }}
            password: ${{ secrets.BLUESKY_PASSWORD }}
            link-preview-url: "https://rivalsstats.com"
            tags: "marvel,rivals,rocket,data-science"
