name: Socials post

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: "00 18 * * *"  # Runs at 18:00 every day

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      start_time: ${{ steps.get_time.outputs.start_time }}
      biggest_positive_hero: ${{ steps.extract_hotlist.outputs.biggest_positive_hero }}
      biggest_positive_winrate: ${{ steps.extract_hotlist.outputs.biggest_positive_winrate }}
      biggest_negative_hero: ${{ steps.extract_hotlist.outputs.biggest_negative_hero }}
      biggest_negative_winrate: ${{ steps.extract_hotlist.outputs.biggest_negative_winrate }}
    steps:  
      - name: Clone project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # gets git history for changelogs
          token: ${{ secrets.WORKFLOW_TOKEN }} 
      - name: Get Time
        id: get_time
        shell: bash
        run: |
          echo "start_time=$(TZ=":Europe/Berlin" date '+%m/%d/%Y')" >> $GITHUB_OUTPUT
      - name: Extract hotlist info
        id: extract_hotlist
        run: |
          # Extract the hero with the maximum positive winrate shift
          pos_hero=$(jq -r '.hotlist_data[0] | max_by(.winrate_shift) | .hero' rendered/data.json)
          pos_winrate=$(jq -r '.hotlist_data[0] | max_by(.winrate_shift) | .win_rate' rendered/data.json)
          
          # Extract the hero with the minimum (most negative) winrate shift
          neg_hero=$(jq -r '.hotlist_data[0] | min_by(.winrate_shift) | .hero' rendered/data.json)
          neg_winrate=$(jq -r '.hotlist_data[0] | min_by(.winrate_shift) | .win_rate' rendered/data.json)
          
          echo "biggest_positive_hero=$pos_hero" >> $GITHUB_OUTPUT
          echo "biggest_positive_winrate=$pos_winrate" >> $GITHUB_OUTPUT
          echo "biggest_negative_hero=$neg_hero" >> $GITHUB_OUTPUT
          echo "biggest_negative_winrate=$neg_winrate" >> $GITHUB_OUTPUT
          


            
  twitter:
    if: FALSE
    needs: setup
    runs-on: ubuntu-latest
    steps:  
      - name: Clone project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # gets git history for changelogs
          token: ${{ secrets.WORKFLOW_TOKEN }} 
      - uses: nearform-actions/github-action-notify-twitter@v1.2.3
        with:
          message: |
            🔥 @MarvelRivals Meta Report for ${{ needs.setup.outputs.start_time }} is out! 🔥
            Biggest Gain - ${{ needs.setup.outputs.biggest_positive_hero }} (Winrate: ${{ needs.setup.outputs.biggest_positive_winrate }}%) 
            Biggest Loss - ${{ needs.setup.outputs.biggest_negative_hero }} (Winrate: ${{ needs.setup.outputs.biggest_negative_winrate }}%)
            Left: Combined Tierlist | Top Right: Ranked by Pickrate | Bottom Right: Ranked by Winrate.
            Full data & analysis: https://rivalsstats.com/
            #MarvelRivals #Tierlist

          twitter-app-key: ${{ secrets.TWITTER_APP_KEY }}
          twitter-app-secret: ${{ secrets.TWITTER_APP_SECRET }}
          twitter-access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          twitter-access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          media: |
            ./rendered/CombinedTierlist.png
            ./rendered/PickrateTierlist.png
            ./rendered/WinrateTierlist.png
          media-alt-text: |
            Pickrate Tierlist
            Winrate Tierlist
            Combined Tierlist
  reddit:
      runs-on: ubuntu-latest
      if: FALSE
      needs: setup
      steps:
        - name: reddit
          uses: meysam81/reddit-scheduled-submit@v1.1.1
          with:
            username: ${{ secrets.REDDIT_USERNAME }}
            password: ${{ secrets.REDDIT_PASSWORD }}
            client-id: ${{ secrets.REDDIT_APP_ID }}
            client-secret: ${{ secrets.REDDIT_APP_SECRET }}
            subreddit: ${{ secrets.REDDIT_SUBREDDIT }}
            title: "Meta Report for ${{ needs.setup.outputs.start_time }} is out!"
            message: |
              Biggest Gain - ${{ needs.setup.outputs.biggest_positive_hero }} (Winrate: ${{ needs.setup.outputs.biggest_positive_winrate }}%) 

              Biggest Loss - ${{ needs.setup.outputs.biggest_negative_hero }} (Winrate: ${{ needs.setup.outputs.biggest_negative_winrate }}%)

              Combined Tierlist: https://rivalsstats.com/rendered/CombinedTierlist.png

              Ranked by Pickrate: https://rivalsstats.com/rendered/PickrateTierlist.png

              Ranked by Winrate: https://rivalsstats.com/rendered/WinrateTierlist.png

              Full data & analysis: https://rivalsstats.com/
  bsky-post:
      runs-on: ubuntu-latest
      needs: setup
      steps:
        - uses: actions/checkout@v3

        - uses: myConsciousness/bluesky-post@v5
          with:
            text: |
              🔥 @marvel-rivals.bsky.social‬ Meta Report for ${{ needs.setup.outputs.start_time }} is out! 🔥
              Biggest Gain - ${{ needs.setup.outputs.biggest_positive_hero }} (Winrate: ${{ needs.setup.outputs.biggest_positive_winrate }}%) 
              Biggest Loss - ${{ needs.setup.outputs.biggest_negative_hero }} (Winrate: ${{ needs.setup.outputs.biggest_negative_winrate }}%)
              Left: Combined Tierlist | Top Right: Ranked by Pickrate | Bottom Right: Ranked by Winrate.
              [Full data & analysis](https://rivalsstats.com)
              #MarvelRivals #Tierlist
            media: |
              ./rendered/CombinedTierlist.png
              ./rendered/PickrateTierlist.png
              ./rendered/WinrateTierlist.png
            media-alt: |
              Pickrate Tierlist
              Winrate Tierlist
              Combined Tierlist
            identifier: ${{ secrets.BLUESKY_IDENTIFIER }}
            password: ${{ secrets.BLUESKY_PASSWORD }}
            link-preview-url: "https://atprotodart.com"
            tags: "marvel,rivals,meta,data-science"
            labels: "marvel,rivals,meta,data-science"
