name: Socials post

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: "00 18 * * *"  # Runs at 18:00 every day

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
            
  twitter:
    if: FALSE
    runs-on: ubuntu-latest
    steps:  
      - name: Clone project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # gets git history for changelogs
          token: ${{ secrets.WORKFLOW_TOKEN }} 
      - uses: nearform-actions/github-action-notify-twitter@v1.2.3
        with:
          message: |
            🔥 Daily @MarvelRivals Meta Report is out! 🔥
            Left: Combined Tierlist | Top Right: Ranked by Pickrate | Bottom Right: Ranked by Winrate.
            Full data & analysis: https://rivalsstats.com/
            #MarvelRivals #Tierlist

          twitter-app-key: ${{ secrets.TWITTER_APP_KEY }}
          twitter-app-secret: ${{ secrets.TWITTER_APP_SECRET }}
          twitter-access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          twitter-access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          media: |
            ./rendered/CombinedTierlist.png
            ./rendered/PickrateTierlist.png
            ./rendered/WinrateTierlist.png
          media-alt-text: |
            Pickrate Tierlist
            Winrate Tierlist
            Combined Tierlist
  reddit:
      runs-on: ubuntu-latest
      steps:
        - name: reddit
          uses: meysam81/reddit-scheduled-submit@v1.1.1
          with:
            username: ${{ secrets.REDDIT_USERNAME }}
            password: ${{ secrets.REDDIT_PASSWORD }}
            client-id: ${{ secrets.REDDIT_APP_ID }}
            client-secret: ${{ secrets.REDDIT_APP_SECRET }}
            subreddit: ${{ secrets.REDDIT_SUBREDDIT }}
            title: "Daily MarvelRivals Meta Report is out!"
            message: |
              Combined Tierlist: https://rivalsstats.com/rendered/CombinedTierlist.png
              Ranked by Pickrate: https://rivalsstats.com/rendered/PickrateTierlist.png
              Ranked by Winrate: https://rivalsstats.com/rendered/WinrateTierlist.png
              Full data & analysis: https://rivalsstats.com/

