name: Socials post

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: "00 18 * * *"  # Runs at 18:00 every day

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # gets git history for changelogs
          token: ${{ secrets.WORKFLOW_TOKEN }}  
      - uses: nearform-actions/github-action-notify-twitter@v1.2.3
        with:
          message: |
            🔥 Daily @MarvelRivals Meta Report is out! 🔥
            Left: Combined Tierlist | Top Right: Ranked by Pickrate | Bottom Right: Ranked by Winrate.
            Full data & analysis: https://rivalsstats.com/
            #MarvelRivals #Tierlist

          twitter-app-key: ${{ secrets.TWITTER_APP_KEY }}
          twitter-app-secret: ${{ secrets.TWITTER_APP_SECRET }}
          twitter-access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          twitter-access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          media: |
            ./rendered/CombinedTierlist.png
            ./rendered/PickrateTierlist.png
            ./rendered/WinrateTierlist.png
          media-alt-text: |
            Pickrate Tierlist
            Winrate Tierlist
            Combined Tierlist

